-- Generated by `npm run seed:sql` from content/*.ts. Do not edit by hand.
-- Run after supabase/migrations/0001_portfolio_cms.sql. Existing rows are
-- left untouched, so re-running never overwrites admin edits.
--
-- To RESET a document to its default instead, replace its
--   on conflict (key) do nothing;
-- with
--   on conflict (key) do update set data = excluded.data;

insert into public.portfolio_documents (key, data)
values ('profile', $seed${
  "name": "Sriram Bharath",
  "role": "College Student (CSE)",
  "tagline": "🛡️ Aspiring Ethical Hacker and Cybersecurity Expert focused on defending the digital world",
  "status": "Active",
  "email": "srirambharath7@gmail.com",
  "githubUsername": "SriramBharath-7",
  "socials": [
    {
      "id": "github",
      "label": "GitHub",
      "url": "https://github.com/SriramBharath-7",
      "handle": "github.com/SriramBharath-7",
      "enabled": true
    },
    {
      "id": "linkedin",
      "label": "LinkedIn",
      "url": "https://linkedin.com/in/sriram-bharath-852335306/",
      "handle": "linkedin.com/in/sriram-bharath-852335306/",
      "enabled": true
    },
    {
      "id": "email",
      "label": "Email",
      "url": "mailto:srirambharath7@gmail.com",
      "handle": "srirambharath7@gmail.com",
      "enabled": true
    }
  ]
}$seed$::jsonb)
on conflict (key) do nothing;

insert into public.portfolio_documents (key, data)
values ('about', $seed${
  "headline": "🛡️ Aspiring Ethical Hacker and Cybersecurity Expert",
  "sections": [
    {
      "id": "about-me",
      "title": "ABOUT ME",
      "body": "I'm a passionate Computer Science Engineering student with a deep interest in cybersecurity, ethical hacking, and information security. Currently pursuing my degree while actively learning and practicing security concepts."
    },
    {
      "id": "programming-languages",
      "title": "PROGRAMMING LANGUAGES",
      "bullets": [
        {
          "label": "Python",
          "description": "Learning automation and security tools development",
          "highlightClass": "lang-python"
        },
        {
          "label": "Bash",
          "description": "System automation and basic scripting",
          "highlightClass": "lang-bash"
        },
        {
          "label": "PowerShell",
          "description": "Windows system administration basics",
          "highlightClass": "lang-ps"
        },
        {
          "label": "Java",
          "description": "Object-oriented programming fundamentals",
          "highlightClass": "lang-java"
        },
        {
          "label": "HTML/CSS/JS",
          "description": "Web development basics",
          "highlightClass": "lang-html"
        },
        {
          "label": "Markdown",
          "description": "Documentation and content creation",
          "highlightClass": "lang-markdown"
        }
      ]
    },
    {
      "id": "learning-areas",
      "title": "LEARNING AREAS",
      "bullets": [
        {
          "label": "Network Security",
          "description": "Understanding protocols and vulnerabilities",
          "highlightClass": "skill-highlight"
        },
        {
          "label": "Web Security",
          "description": "Learning about OWASP Top 10 and web vulnerabilities",
          "highlightClass": "skill-highlight"
        },
        {
          "label": "Penetration Testing",
          "description": "Ethical hacking methodologies",
          "highlightClass": "skill-highlight"
        },
        {
          "label": "OSINT",
          "description": "Open source intelligence gathering techniques",
          "highlightClass": "skill-highlight"
        }
      ]
    },
    {
      "id": "education-goals",
      "title": "EDUCATION & GOALS",
      "bullets": [
        {
          "label": "Bachelor of Engineering in Computer Science (In Progress)"
        },
        {
          "label": "Learning cybersecurity fundamentals and ethical hacking concepts"
        },
        {
          "label": "Planning to pursue certifications like CEH, CompTIA Security+, and OSCP"
        },
        {
          "label": "Active participation in CTF challenges and security communities"
        }
      ]
    },
    {
      "id": "interests",
      "title": "INTERESTS",
      "body": "Passionate about understanding how systems work, finding vulnerabilities, and learning defensive security measures. Currently focused on building a strong foundation in cybersecurity concepts, tools, and methodologies."
    },
    {
      "id": "projects",
      "title": "PROJECTS",
      "body": "Working on various cybersecurity projects including vulnerability assessment tools, security awareness applications, and learning platforms. Always eager to contribute to open-source security projects and collaborate with the cybersecurity community."
    }
  ]
}$seed$::jsonb)
on conflict (key) do nothing;

insert into public.portfolio_documents (key, data)
values ('education', $seed${
  "headline": "My Education",
  "entries": [
    {
      "id": "be-cse",
      "degree": "Bachelor of Engineering in Computer Science",
      "status": "Currently pursuing",
      "coursework": [
        "Computer Networks and Security",
        "Operating Systems",
        "Programming Fundamentals",
        "Data Structures and Algorithms",
        "Web Technologies",
        "Database Management Systems"
      ],
      "notes": "Currently learning cybersecurity concepts and ethical hacking methodologies."
    }
  ],
  "goals": [
    {
      "id": "ceh",
      "title": "CEH (Certified Ethical Hacker)",
      "description": "Planning to pursue"
    },
    {
      "id": "security-plus",
      "title": "CompTIA Security+",
      "description": "Foundation certification goal"
    },
    {
      "id": "oscp",
      "title": "OSCP (Offensive Security Certified Professional)",
      "description": "Long-term goal"
    },
    {
      "id": "ctf",
      "title": "Active participation in CTF challenges and security communities"
    }
  ]
}$seed$::jsonb)
on conflict (key) do nothing;

insert into public.portfolio_documents (key, data)
values ('skills', $seed${
  "headline": "Programming Languages & Technical Skills",
  "intro": "Learning and practicing:",
  "groups": [
    {
      "id": "languages",
      "title": "Languages & Scripting",
      "items": [
        {
          "id": "python",
          "name": "Python",
          "description": "Automation and security tools development",
          "highlightClass": "lang-python"
        },
        {
          "id": "bash",
          "name": "Bash Scripting",
          "description": "System automation and basic scripting",
          "highlightClass": "lang-bash"
        },
        {
          "id": "powershell",
          "name": "PowerShell",
          "description": "Windows system administration basics",
          "highlightClass": "lang-ps"
        },
        {
          "id": "java",
          "name": "Java",
          "description": "Object-oriented programming fundamentals",
          "highlightClass": "lang-java"
        },
        {
          "id": "web",
          "name": "HTML/CSS/JavaScript",
          "description": "Web development basics",
          "highlightClass": "lang-html"
        },
        {
          "id": "markdown",
          "name": "Markdown",
          "description": "Documentation and content creation",
          "highlightClass": "lang-markdown"
        }
      ]
    }
  ],
  "interests": [
    "Network security",
    "web security",
    "penetration testing",
    "OSINT"
  ]
}$seed$::jsonb)
on conflict (key) do nothing;

insert into public.portfolio_documents (key, data)
values ('certifications', $seed$[
  {
    "id": "how-to-use-ai",
    "title": "How to use AI effectively",
    "status": "Completed",
    "completed": "2025-04-22",
    "description": "Fundamentals of leveraging AI tools efficiently for learning and productivity.",
    "image": "/assets/certs/How%20to%20use%20Ai.jpg"
  },
  {
    "id": "ztm-efficient-learning",
    "title": "ZTM – Efficient Learning",
    "provider": "Zero To Mastery",
    "status": "Completed",
    "completed": "2025-04-20",
    "description": "Techniques and frameworks for mastering topics faster with deliberate practice.",
    "image": "/assets/certs/ZTM%20%5BEfficient%20Learning%5D.png"
  },
  {
    "id": "ai-career-coach",
    "title": "AI Career Coach",
    "status": "Completed",
    "completed": "2025-04-20",
    "description": "Guidance on building an AI-focused career: positioning, portfolios, and growth roadmap.",
    "image": "/assets/certs/AI%20Career%20Coath.png"
  }
]$seed$::jsonb)
on conflict (key) do nothing;

insert into public.portfolio_documents (key, data)
values ('ctf', $seed${
  "headline": "Capture The Flag Learning Journey",
  "intro": "Currently learning and participating in:",
  "focusAreas": [
    "CTF challenges and competitions",
    "Web exploitation and security testing",
    "Reverse engineering concepts",
    "Cryptography and encoding challenges",
    "Network security challenges"
  ],
  "closing": "Building experience through hands-on practice and community participation."
}$seed$::jsonb)
on conflict (key) do nothing;

insert into public.portfolio_documents (key, data)
values ('tools', $seed${
  "headline": "Security Tools & Learning Projects",
  "intro": "Learning and experimenting with:",
  "items": [
    "Security assessment tools and frameworks",
    "Network analysis and monitoring tools",
    "Web vulnerability scanners",
    "Security automation scripts",
    "Educational security projects"
  ],
  "closing": "Focusing on understanding how security tools work and developing basic security applications."
}$seed$::jsonb)
on conflict (key) do nothing;

insert into public.portfolio_documents (key, data)
values ('blog', $seed${
  "devtoUsername": "sriram_bharath",
  "mediumHandle": "@srirambharath7"
}$seed$::jsonb)
on conflict (key) do nothing;

insert into public.portfolio_documents (key, data)
values ('projects', $seed${
  "excludeForks": true,
  "repos": [
    {
      "name": "OS_PORTFOLIO",
      "hidden": true
    }
  ]
}$seed$::jsonb)
on conflict (key) do nothing;

insert into public.portfolio_documents (key, data)
values ('apps', $seed$[
  {
    "id": "terminal",
    "kind": "terminal",
    "name": "Terminal",
    "icon": "/assets/svg/terminal.svg",
    "enabled": true,
    "showOnDesktop": true,
    "showInTaskbar": true
  },
  {
    "id": "firefox",
    "kind": "browser",
    "name": "Firefox",
    "icon": "/assets/svg/firefox.svg",
    "enabled": true,
    "showOnDesktop": true,
    "showInTaskbar": true,
    "url": "home://start"
  }
]$seed$::jsonb)
on conflict (key) do nothing;

insert into public.portfolio_documents (key, data)
values ('commands', $seed$[
  {
    "id": "github",
    "name": "github",
    "aliases": [
      "gh"
    ],
    "description": "Open my GitHub profile",
    "help": "Opens github.com/SriramBharath-7 in a new browser tab.",
    "enabled": false,
    "response": {
      "type": "url",
      "url": "https://github.com/SriramBharath-7"
    }
  },
  {
    "id": "quote",
    "name": "quote",
    "aliases": [],
    "description": "Print a favourite security quote",
    "enabled": false,
    "response": {
      "type": "text",
      "text": "\"Security is a process, not a product.\" — Bruce Schneier"
    }
  }
]$seed$::jsonb)
on conflict (key) do nothing;

insert into public.portfolio_documents (key, data)
values ('settings', $seed${
  "welcome": {
    "enabled": true,
    "title": "Welcome to My Portfolio",
    "heading": "Terminal Interaction",
    "message": "Click **Terminal** icon for CLI. Type `help` for commands.",
    "callToAction": "Click Terminal to begin exploring",
    "autoCloseSeconds": 5
  },
  "boot": {
    "messages": [
      "Initializing Sriram's Portfolio",
      "Checking Device Compatibility",
      "Loading Resources",
      "Preparing Environment"
    ]
  },
  "terminal": {
    "motd": [
      "Kali GNU/Linux Rolling · 6.8.0-kali3-amd64",
      "Type `help` for available commands, `neofetch` for an overview."
    ]
  },
  "githubWidget": {
    "enabled": true,
    "url": "https://github.com/SriramBharath-7/sriram-portfolio",
    "label": "Star on GitHub",
    "caption": "Support the project"
  }
}$seed$::jsonb)
on conflict (key) do nothing;
