/**
 * Writes supabase/seed.sql from the static defaults in content/.
 *
 *   npm run seed:sql
 *
 * Every default is validated against the same schema the admin uses, so a
 * default that would be rejected on save fails here instead of in production.
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { DEFAULT_DOCUMENTS, DOCUMENT_KEYS, type PortfolioDocuments } from "../content/documents";
import { validateDocument } from "../content/schema";

/** A dollar-quote tag that does not occur in the payload. */
function dollarTag(payload: string): string {
  let tag = "$seed$";
  for (let n = 1; payload.includes(tag); n++) tag = `$seed${n}$`;
  return tag;
}

export function buildSeedSql(documents: PortfolioDocuments = DEFAULT_DOCUMENTS): string {
  const statements = DOCUMENT_KEYS.map((key) => {
    const result = validateDocument(key, documents[key]);
    if (!result.ok) {
      const detail = result.issues.map((issue) => `${issue.path || "(root)"}: ${issue.message}`);
      throw new Error(`Default "${key}" fails validation:\n  ${detail.join("\n  ")}`);
    }
    const json = JSON.stringify(documents[key], null, 2);
    const tag = dollarTag(json);
    return (
      `insert into public.portfolio_documents (key, data)\n` +
      `values ('${key}', ${tag}${json}${tag}::jsonb)\n` +
      `on conflict (key) do nothing;`
    );
  });

  return [
    "-- Generated by `npm run seed:sql` from content/*.ts. Do not edit by hand.",
    "-- Run after supabase/migrations/0001_portfolio_cms.sql. Existing rows are",
    "-- left untouched, so re-running never overwrites admin edits.",
    "--",
    "-- To RESET a document to its default instead, replace its",
    "--   on conflict (key) do nothing;",
    "-- with",
    "--   on conflict (key) do update set data = excluded.data;",
    "",
    ...statements.map((statement) => `${statement}\n`),
  ].join("\n");
}

function main() {
  const target = join(process.cwd(), "supabase", "seed.sql");
  writeFileSync(target, buildSeedSql());
  console.log(`Wrote ${target}`);
}

// Only write when run as a script, not when imported by a test.
if (process.argv[1]?.replace(/\\/g, "/").endsWith("scripts/generate-seed.ts")) main();
